name: storytown

dependencies:
  - base
  - aeson
  - wai
  - wai-cors
  - wai-make-assets
  - wai-extra
  - warp
  - warp-tls
  - servant-elm
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - optparse-applicative
  - persistent-postgresql
  - persistent
  - persistent-template
  - heroku-persistent
  - amazonka
  - amazonka-s3
  - transformers
  - containers
  - bytestring
  - base64-bytestring
  - monad-logger
  - http-types
  - lens
  - time
  - resourcet
  - text
  - entropy
  - cookie

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src
  aws:
    main: Main.hs
    source-dirs:
      - trial/aws

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
