resolver: lts-8.5

packages:
- .
- location:
    git: https://www.github.com/iteloo/servant-elm
    commit: 7d77deb
  extra-dep: True
- location:
    git: https://www.github.com/iteloo/amazonka
    commit: 22440edf20d697595a461547ed72d244ba70ef28
  subdirs:
  - amazonka-s3
  extra-dep: True
- location:
    git: https://www.github.com/iteloo/servant-auth
    commit: 7887155d54c9f9ba8a5350962b1530b4296c69f3
  subdirs:
  - servant-auth-server
  extra-dep: True


# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- heroku-persistent-0.2.0
- servant-auth-0.2.6.1
- servant-auth-server-0.2.6.1
- wai-make-assets-0.2
- heroku-0.1.2.3
