resolver: lts-7.14

packages:
- .
- location:
    git: https://www.github.com/soenkehahn/wai-make-assets
    commit: c72a924
  extra-dep: true
- location:
    git: https://www.github.com/iteloo/servant-elm
    commit: 70d6299f6c4f7b12ab4fd0b307ae860cd35c18eb
  extra-dep: True

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- elm-export-0.5.0.2
- time-1.5.0.1
- heroku-persistent-0.2.0
- heroku-0.1.2.3
- servant-auth-0.2.1.0
- servant-auth-server-0.2.1.0
- jose-0.5.0.2
